# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='egresados',
            fields=[
                ('cedula', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
            ],
        ),
    ]
