# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_conocimiento',
            name='estatus',
            field=models.BooleanField(max_length=1),
        ),
    ]
