# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0003_publicacion_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='canal',
            field=models.TextField(null=True),
        ),
    ]
